# Generated by Django 4.2.5 on 2024-12-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_faculty_created_at_remove_faculty_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_org', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
                ('yoe', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=256)),
                ('profiles', models.CharField(max_length=256)),
                ('pos_available', models.PositiveIntegerField()),
                ('work_mode', models.CharField(max_length=100)),
                ('job_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('stipend', models.CharField(blank=True, max_length=256, null=True)),
                ('poc_name', models.CharField(max_length=256)),
                ('poc_email', models.EmailField(max_length=254)),
                ('poc_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
