# Generated by Django 4.2.5 on 2024-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_intern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='poc_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='poc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='poc_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
