# Generated by Django 4.2.5 on 2024-12-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_intern_poc_contact_alter_intern_poc_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='profiles',
            field=models.JSONField(default=list),
        ),
    ]
